apiVersion: v1
kind: Namespace
metadata:
  name: winovk8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: winovk8s-app
  namespace: winovk8s
  labels:
    app: winovk8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: winovk8s
  template:
    metadata:
      labels:
        app: winovk8s
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: nginx
          image: nginx:1.25.3
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
        - name: consul
          image: hashicorp/consul:1.16.2
          ports:
            - containerPort: 8500
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: winovk8s
spec:
  selector:
    app: winovk8s
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: consul-service
  namespace: winovk8s
spec:
  selector:
    app: winovk8s
  ports:
    - port: 8500
      targetPort: 8500
      protocol: TCP
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: winovk8s-ingress
  namespace: winovk8s
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: winovk8s.example.com
      http:
        paths:
          - path: /nginx
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
          - path: /consul
            pathType: Prefix
            backend:
              service:
                name: consul-service
                port:
                  number: 8500

