---
- name: Install NFS Kernel Server
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
  become: yes

- name: Create shared directory
  ansible.builtin.file:
    path: /nfs/winov-data
    state: directory
    owner: nobody
    group: nogroup
    mode: '0777'
  become: yes

- name: Configure exportsfs
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify: Restart NFS Server
  become: yes
