---
- name: Root Login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin\s+'
    line: 'PermitRootLogin prohibit-password'
    backup: yes

- name: Create .ssh directory
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: Add public key
  ansible.builtin.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', 'files/ssh.txt') }}"

- name: Install NFS Common
  ansible.builtin.apt:
    name:
      - nfs-common
    state: present
    update_cache: yes
  become: yes